# bash_profile is executed for login shells (login and ssh)
# shellcheck shell=bash

# echo "bash_profile start"

# shellcheck source=/dev/null
if [ -f ~/.profile ]; then
   source ~/.profile
fi

# shellcheck source=/dev/null
if [ -f ~/.bashrc ]; then
   source ~/.bashrc
fi

# mac specific additions
# shellcheck source=/dev/null
if [[ $OSTYPE == 'darwin'* ]]; then
  export BASH_SILENCE_DEPRECATION_WARNING=1
fi

#echo "bash_profile end"
