# -------------------
# Aliases
# -------------------

# This allows sudo to work with aliases
alias sudo='sudo '

# does what it should
alias untar="tar -xf"

# make grep use color
# DEPRECATED: export GREP_OPTIONS="--color=auto"
alias grep='grep --color=auto'

# search code faster
alias cgrep='grep --color=always -RIin'

# ls aliases
if [ "$(uname)" = "Darwin" ]; then
    alias ls='ls -G'
else
    alias ls='ls --color=auto'
fi

# print dd status
alias dd-status='pkill -USR1 ^dd'


# netstat the way I like it
alias ports='netstat -tupl --numeric-ports | grep -E ":[0-9]+\s"'
alias portse='netstat -tup --numeric-ports | grep -E ":[0-9]+\s"'

# dmesg with readable time
alias dmesg='dmesg -T'

# I use du -sh way to much
alias s="du -sh"

# force mtr to text mode
alias mtr='mtr -t'

# faster opens
alias o='gnome-open'

# get my ip
alias myip='curl curlmyip.com'

# incognito
alias incogterm='unset HISTFILE'

# fix htop inside tmux
alias htop="TERM=screen htop"

# htop for only current user
alias utop='htop -u $USER'

alias csort="LC_COLLATE=C sort"

# faster tmux resume
alias t="tmux"
alias ta="tmux a"

#alias subl="subl -n"
alias sn="subl -n ."

# send myself email notifications
alias pong="mail -s PONG $USER"

# upload command output to clbin
alias clbin="curl -F 'clbin=<-' https://clbin.com"

# cleaner docker ps
alias dps="docker ps -a --format \"table {{.ID}}\t{{.Names}}\t{{.Status}}\t{{.Image}}\""
