# bash_profile is executed for login shells (login and ssh)

if [ -f ~/.profile ]; then
   source ~/.profile
fi

if [ -f ~/.bashrc ]; then
   source ~/.bashrc
fi

export BASH_SILENCE_DEPRECATION_WARNING=1

# use firefox wayland if using wayland
if [ "$XDG_SESSION_TYPE" == "wayland" ]; then
    export MOZ_ENABLE_WAYLAND=1
    if command -v code &>/dev/null
    then
        alias code="code --ozone-platform-hint=auto --enable-features=WaylandWindowDecorations"
    fi
fi

