# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi
#For mac colors.
if [ `uname` == 'Darwin' ]
then
    export CLICOLOR=1
    export LSCOLORS=GxFxCxDxBxegedabagaced
    #Mac specific ALIAS'
    alias vi=edit $@
fi

#Initial standard colored terminal
MYDIR="[\[\033[33;1m\]\w\[\033[m\]]\n"
PS1="$MYDIR[\[\033[36m\]\u\[\033[m\]@\[\033[32m\]\h]\$ "

#source ~/perl5/perlbrew/etc/bashrc

# User specific aliases and functions
alias ls="ls -p"
