#bind-addr: 127.0.0.1:8099
auth: none
cert: false
# allow reverse proxy
trusted-origins:
  - '*'
disable-telemetry: true
disable-update-check: true
disable-getting-started-override: true
socket: .local/code-server/code-server.sock
