" ##########################################
"               Vim Settings
" ##########################################

" This setting prevents vim from emulating the original vi's bugs and limitations.
set nocompatible

" Remove Lag
set ttyfast

" Map ; to : in normal mode for mega-easy vim commands.
nnoremap ; :

" Encoding
set encoding=utf-8  " Set file encoding
"set termencoding=utf-8

"The first setting tells vim to use 'autoindent' (that is, use the current
"line's indent level to set the indent level of new lines). The second makes
"vim attempt to intelligently guess the indent level of any new line based on
"the previous line, assuming the source file is in a C-like language.
"Combined, they are very useful in writing well-formatted source code.
set autoindent
set smartindent

"Use 4-space tabs. The first setting sets up 4-space
"tabs, and the second tells vi to use 4 spaces when text is indented
set tabstop=4
set shiftwidth=4 "indent width for autoindent
set expandtab " no real tabs please, turn tabs into whitespace
set shiftround " when at 3 spaces, and I hit > ... go to 4, not 5
set softtabstop=4 " when hitting tab or backspace, how many spaces should a tab be (see expandtab)
filetype plugin indent on "indent depends on filetype

"ignore whitespace in vimdiff
if &diff
    " diff mode
    set diffopt+=iwhite
endif

"allow tabs on makefiles
autocmd FileType make setlocal noexpandtab
autocmd FileType go setlocal noexpandtab

"aura cmp files
au BufNewFile,BufRead *.cmp set filetype=html

" show matching brackets
set showmatch

"This setting ensures that each window contains a statusline that displays the
"current cursor position.
set ruler

"With this nifty option, vim will search for text as you enter it.
set incsearch
"highlight search results
set hlsearch

"ignore search case with all lowercase, use case when all uppercase
set ignorecase
set smartcase

"syntax stuff
syntax on
syntax sync fromstart "increases syntax accuracy
"go
au BufReadPost *.go set filetype=go

"STFU
set noerrorbells
set vb t_vb=""

" use mouse everywhere
set mouse=a

" turn on command line completion wild style
set wildmenu

"ignore these list file extensions
set wildignore=*.dll,*.o,*.obj,*.exe,*.pyc,*.jpg,*.gif,*.png,*.class,*.ln
set wildmode=list:longest " turn on wild mode huge list

"Keep the cursor n lines from the top and bottom
set scrolloff=2
set sidescrolloff=4 " Keep n lines at the side

" always show the status line
set laststatus=2

" we do what to show tabs, to ensure we get them  out of my files
set list
" show tabs and trailing
set listchars=tab:>-,trail:-

"show line numbers
set number

" Show number of lines changed by : commands
set report=0

" show the command being typed
set showcmd

" do not wrap line
set nowrap
"if we do ever decide to wrap display a nice wrap image
set showbreak=↪
" use softwrap
set linebreak
set nolist  " list disables linebreak

"statusline
"replaced by vim-powerline plugin
"set statusline=%F%m%r%h%w\ [%Y,%{&ff}]\ [%l/%L,%c][%p%%]

"Highlight current line
set cursorline

" make backspace always work
set backspace=indent,eol,start

" toggle paste mode
set pastetoggle=<F2>

" toggle spellcheck
map <F7> :setlocal spell! spelllang=en_us<CR>
"imap <F7> <C-o>:setlocal spell! spelllang=en_us<CR>
imap <F7> ea<C-X><C-S>
nnoremap \s ea<C-X><C-S>

" make up/down work in warp-mode
nnoremap <Up> gk
nnoremap <Down> gj
" TODO make isnert mode work
imap <silent> <Up> <C-o>gk
imap <silent> <Down> <C-o>gj
" ##########################################
"               Plugin Code
" ##########################################
"start pathogen to load all plugins
runtime bundle/vim-pathogen/autoload/pathogen.vim
execute pathogen#infect()


" key used to launch nerdtree
map <C-d> :NERDTreeToggle<CR>
map <F6> :NERDTreeToggle<CR>
" have nerdtree open when vim started wih no file
autocmd vimenter * if !argc() | NERDTree | endif
" close nerdtree if it is the last window open
autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTreeType") && b:NERDTreeType == "primary") | q | endif
" have nerdtree ignore certian file types
let NERDTreeIgnore=['\.o$', '\~$', '\.ln', '\.class', '\.pyc']

"color scheme
set t_Co=256 "this forces vim to use 256 colors even if the console says it is not supported
"set background=dark
colorscheme jellybeans

"powerline statusbar
"let g:Powerline_symbols = 'fancy' "does not work with vim-tiny

"tagbar
"requires ctags [exuberant-ctags] to be installed
nmap <F8> :TagbarToggle<CR>

" ##########################################
"               Testing
" ##########################################

"auto-backup
"set backup
"#set backupdir     =$HOME/.vim/backup/
"set backupext     =.bak

"keep temp files in separate dir
"set directory     =$HOME/.vim/tmp/swap/
" set viminfo       ='100,n$HOME/.vim/tmp/viminfo

"Enable indent folding
"set foldenable
"set fdm=indent

"fix arrow key problem with indent plugin
set ttimeout
set ttimeoutlen=100

