#!/usr/bin/env bash

docker_cli_plugin_metadata() {
	local vendor="lanrat"
	local description="remove untagged images"
	cat <<-EOF
	{"SchemaVersion":"0.1.0","Vendor":"${vendor}","ShortDescription":"${description}"}
EOF
}

docker-clean-images() {
    images="$(docker image ls -q --filter=dangling=true)"
	if [ -z "$images" ]; then
		echo "no images to clean"
	else
		# shellcheck disable=SC2086
    	docker image rm $images
	fi
}

case "$1" in
	docker-cli-plugin-metadata)
		docker_cli_plugin_metadata
		;;
	__completeNoDesc)
		echo " "
		;;
	*)
        docker-clean-images
		;;
esac
