#!/usr/bin/env bash

docker_cli_plugin_metadata() {
	local vendor="lanrat"
	local description="list container networks"
	cat <<-EOF
	{"SchemaVersion":"0.1.0","Vendor":"${vendor}","ShortDescription":"${description}"}
EOF
}

docker-net() {
	query="$1"
	if [ -z "${1}" ]; then
		query="$(docker network ls --format '{{.Name}}')"
	fi
	docker network inspect --format "{{.Name}}|{{.Driver}}|{{(index .IPAM.Config 0).Subnet}}|{{range \$i, \$v := .Containers}}{{\$v.Name}}:{{\$v.IPv4Address}}|{{end}}" $query | column -ts\|
}

# docker tail completions
_complete_docker_containers () {
	COMPREPLY=()
	#cur="${COMP_WORDS[COMP_CWORD]}"
	cur="$1"
	comp_docker_containers="$(docker network ls --format '{{.Name}}')"
	COMPREPLY=( $(compgen -W "${comp_docker_containers}" -- "$cur"))
	if [ "${#COMPREPLY}" -gt "0" ]; then
    	echo "${COMPREPLY[*]}"
	else
		echo " " # space terminated the completion
	fi
	return 0
}

case "$1" in
	docker-cli-plugin-metadata)
		docker_cli_plugin_metadata
		;;
	__completeNoDesc)
		#__docker_complete_containers_all --cur "${2##*=}"
		arg=("${@:2}")
		_complete_docker_containers "${arg[*]}"
		;;
	*)
        docker-net "$2"
		;;
esac
