#!/usr/bin/env bash

docker_cli_plugin_metadata() {
	local vendor="lanrat"
	local description="tail -f for docker services"
	cat <<-EOF
	{"SchemaVersion":"0.1.0","Vendor":"${vendor}","ShortDescription":"${description}"}
EOF
}

docker-tail() {
	set -e
    while true; do
		until [ "$(docker inspect -f "{{.State.Running}}" "$1" 2>/dev/null)" == "true" ]; do
			sleep 0.1;
		done;
		docker logs --tail=50 -f "$1"
	done
}

## TODO use completion functions here
# https://github.com/docker/cli/pull/4094
# https://github.com/docker/cli/blob/master/contrib/completion/bash/docker


# docker tail completions
_complete_docker_containers () {
	COMPREPLY=()
	#cur="${COMP_WORDS[COMP_CWORD]}"
	cur="$1"
	comp_docker_containers="$(docker ps -a --format '{{.Names}}')"
	COMPREPLY=( $(compgen -W "${comp_docker_containers}" -- "$cur"))
	if [ "${#COMPREPLY}" -gt "0" ]; then
    	echo "${COMPREPLY[*]}"
	else
		echo " " # space terminated the completion
	fi
	return 0
}

case "$1" in
	docker-cli-plugin-metadata)
		docker_cli_plugin_metadata
		;;
	__completeNoDesc)
		#__docker_complete_containers_all --cur "${2##*=}"
		arg=("${@:2}")
		_complete_docker_containers "${arg[*]}"
		;;
	*)
        docker-tail "$2"
		;;
esac
