#!/bin/sh
# pass -incognito for incognito mode
TMP="/tmp"
chrome="google-chrome"
if [[ "$OSTYPE" == "linux-gnu" ]]; then
    chrome="google-chrome"
    TMP="/dev/shm"
    if type "bwrap" > /dev/null; then
        echo "Using bubblewrap container"
        # I could also set the user-data-dir to a tmpfs dir in bwrap if I want
        chrome="bwrap --dev-bind / / --tmpfs /etc/opt/chrome $chrome"
    fi
elif [[ "$OSTYPE" == "darwin"* ]]; then
    chrome="/Applications/Google Chrome.app/Contents/MacOS/Google Chrome"
else
    echo "Unknown OS $OSTYPE"
    exit 1
fi
TMPDIR=$(mktemp -d $TMP/chrome-XXXXX)
echo "Using TMPDIR: $TMPDIR"
$chrome --user-data-dir="$TMPDIR" --no-first-run --no-make-default-browser "$@"
rm -rf "$TMPDIR"
