#!/usr/bin/env bash
set -eu
set -o pipefail
if [[ "${TRACE-0}" == "1" ]]; then set -o xtrace; fi

# TODO switch to chrome guest mode --guest flag

# pass -incognito for incognito mode
TMP="/tmp"
chrome="google-chrome"
if [[ "$OSTYPE" == "linux-gnu" ]]; then
    chrome="google-chrome"
    TMP="/dev/shm"
    if type "bwrap" > /dev/null; then
        echo "Using bubblewrap container"
        # I could also set the user-data-dir to a tmpfs dir in bwrap if I want
        tmpfs=""
        if [ -d "/etc/opt/chrome" ]; then
          tmpfs="--tmpfs /etc/opt/chrome"
        fi
        chrome="bwrap --dev-bind / / $tmpfs $chrome"
    fi
elif [[ "$OSTYPE" == "darwin"* ]]; then
    chrome="/Applications/Google Chrome.app/Contents/MacOS/Google Chrome"
else
    echo "Unknown OS $OSTYPE"
    exit 1
fi
TMPDIR=$(mktemp -d $TMP/chrome-XXXXX)
echo "Using TMPDIR: $TMPDIR"
$chrome --user-data-dir="$TMPDIR" \
  --no-first-run \
  --no-make-default-browser \
  --no-default-browser-check \
  --disable-client-side-phishing-detection \
  --disable-component-update \
  --disable-sync \
  --disable-translate \
  --safebrowsing-disable-auto-update \
  --safebrowsing-disable-download-protection \
  --use-mock-keychain \
  --no-sandbox \
  $@

rm -rf "$TMPDIR"
