#!/usr/bin/env bash
set -eu
set -o pipefail
if [[ "${TRACE-0}" == "1" ]]; then set -o xtrace; fi


chrome="google-chrome"
if [[ "$OSTYPE" == "linux-gnu" ]]; then
    chrome="google-chrome"
elif [[ "$OSTYPE" == "darwin"* ]]; then
    chrome="/Applications/Google Chrome.app/Contents/MacOS/Google Chrome"
else
    echo "Unknown OS $OSTYPE"
    exit 1
fi

data_dir="$HOME/.config/google-chrome-mcp"
echo "Using data_dir: $data_dir"

"$chrome" \
    --user-data-dir="$data_dir" \
    --no-first-run \
    --no-make-default-browser \
    --force-dark-mode \
    --disable-component-update \
    --disable-sync \
    --disable-translate \
    --safebrowsing-disable-auto-update \
    --safebrowsing-disable-download-protection \
    --use-mock-keychain \
    "$@"
