#!/bin/sh
CONNECTED_OUTPUTS=$(xrandr -q | grep "\Wconnected" | cut -d ' ' -f1)
DISCONNECTED_OUTPUTS=$(xrandr -q | grep "\Wdisconnected" | cut -d ' ' -f1)
PRIMARY_DISPLAY=$(echo $CONNECTED_OUTPUTS | cut -f1 -d " ")
SECONDARY_DISPLAY=$(echo $CONNECTED_OUTPUTS | cut -f2 -d " ")


disable()
{
    for output in $DISCONNECTED_OUTPUTS;
    do
        xrandr --output $output --off
    done
}

enable_auto()
{
    prev=''
    for output in $CONNECTED_OUTPUTS;
    do
        xrandr --output $output --auto $prev
        prev="--right-of $output"
    done
}

enable_up()
{
    ext_h=`xrandr | sed 's/^'"${SECONDARY_DISPLAY}"' [^0-9]* [0-9]\+x\([0-9]\+\).*$/\1/p;d'`
    ext_w=`xrandr | sed 's/^'"${SECONDARY_DISPLAY}"' [^0-9]* \([0-9]\+\)x.*$/\1/p;d'`
    int_w=`xrandr | sed 's/^'"${PRIMARY_DISPLAY}"' [^0-9]* \([0-9]\+\)x.*$/\1/p;d'`

    off_w=`echo $(( ($ext_w-$int_w)/2 )) | sed 's/^-//'`

    xrandr \
        --output $PRIMARY_DISPLAY --preferred --pos ${off_w}x${ext_h} \
        --output $SECONDARY_DISPLAY --preferred --pos 0x0
}

#diable old
disable


if [ $? -eq 0 ];
then
    enable_up
else
    enable_auto
fi

